"""Tests for profile config inheritance from root config.

Verifies that when a profile config is loaded, it inherits dict-valued
keys (providers, custom_providers, credential_pool_strategies) from the
root (default profile) config instead of replacing them.
"""

import os
import textwrap
from unittest.mock import patch

import pytest


class TestProfileConfigInheritance:
    """Verify that profile configs inherit from the root config."""

    def test_profile_inherits_root_providers(self, tmp_path, monkeypatch):
        """Profile config should inherit providers from root config.yaml."""
        # Setup: root config with providers
        root_home = tmp_path / "root"
        root_home.mkdir()
        (root_home / "config.yaml").write_text(textwrap.dedent("""\
            providers:
              openrouter:
                api_key_env: OPENROUTER_API_KEY
              anthropic:
                api_key_env: ANTHROPIC_API_KEY
        """))
        # Setup: profile config with empty providers (as generated by hermes profile create)
        profile_dir = root_home / "profiles" / "builder"
        profile_dir.mkdir(parents=True)
        (profile_dir / "config.yaml").write_text(textwrap.dedent("""\
            model: openrouter/claude-sonnet-4
            providers: {}
        """))

        monkeypatch.setenv("HERMES_HOME", str(profile_dir))

        from hermes_cli.config import load_config, _LOAD_CONFIG_CACHE
        _LOAD_CONFIG_CACHE.clear()

        config = load_config()

        # Profile should inherit providers from root config
        assert "openrouter" in config.get("providers", {})
        assert "anthropic" in config.get("providers", {})
        assert config["providers"]["openrouter"]["api_key_env"] == "OPENROUTER_API_KEY"

    def test_profile_overrides_root_provider(self, tmp_path, monkeypatch):
        """Profile can override a specific provider without losing others."""
        root_home = tmp_path / "root"
        root_home.mkdir()
        (root_home / "config.yaml").write_text(textwrap.dedent("""\
            providers:
              openrouter:
                api_key_env: OPENROUTER_API_KEY
              anthropic:
                api_key_env: ANTHROPIC_API_KEY
        """))
        profile_dir = root_home / "profiles" / "custom"
        profile_dir.mkdir(parents=True)
        (profile_dir / "config.yaml").write_text(textwrap.dedent("""\
            providers:
              openrouter:
                api_key_env: CUSTOM_OR_KEY
        """))

        monkeypatch.setenv("HERMES_HOME", str(profile_dir))

        from hermes_cli.config import load_config, _LOAD_CONFIG_CACHE
        _LOAD_CONFIG_CACHE.clear()

        config = load_config()

        # Profile overrides openrouter, inherits anthropic
        assert config["providers"]["openrouter"]["api_key_env"] == "CUSTOM_OR_KEY"
        assert config["providers"]["anthropic"]["api_key_env"] == "ANTHROPIC_API_KEY"

    def test_no_profile_uses_root_directly(self, tmp_path, monkeypatch):
        """When not using a profile, root config loads as before."""
        root_home = tmp_path / "root"
        root_home.mkdir()
        (root_home / "config.yaml").write_text(textwrap.dedent("""\
            providers:
              openrouter:
                api_key_env: OPENROUTER_API_KEY
        """))

        monkeypatch.setenv("HERMES_HOME", str(root_home))

        from hermes_cli.config import load_config, _LOAD_CONFIG_CACHE
        _LOAD_CONFIG_CACHE.clear()

        config = load_config()

        assert config["providers"]["openrouter"]["api_key_env"] == "OPENROUTER_API_KEY"

    def test_profile_without_root_config_works(self, tmp_path, monkeypatch):
        """Profile with no root config.yaml falls back to DEFAULT_CONFIG."""
        root_home = tmp_path / "root"
        root_home.mkdir()
        # No root config.yaml
        profile_dir = root_home / "profiles" / "isolated"
        profile_dir.mkdir(parents=True)
        (profile_dir / "config.yaml").write_text(textwrap.dedent("""\
            model: test-model
        """))

        monkeypatch.setenv("HERMES_HOME", str(profile_dir))

        from hermes_cli.config import load_config, _LOAD_CONFIG_CACHE
        _LOAD_CONFIG_CACHE.clear()

        config = load_config()

        assert config["model"] == "test-model"
        # providers should be DEFAULT_CONFIG's empty dict
        assert config.get("providers", {}) == {}

    def test_profile_inherits_credential_pool_strategies(self, tmp_path, monkeypatch):
        """credential_pool_strategies is also inherited from root config."""
        root_home = tmp_path / "root"
        root_home.mkdir()
        (root_home / "config.yaml").write_text(textwrap.dedent("""\
            credential_pool_strategies:
              openrouter: round_robin
        """))
        profile_dir = root_home / "profiles" / "worker"
        profile_dir.mkdir(parents=True)
        (profile_dir / "config.yaml").write_text("model: openrouter/test\n")

        monkeypatch.setenv("HERMES_HOME", str(profile_dir))

        from hermes_cli.config import load_config, _LOAD_CONFIG_CACHE
        _LOAD_CONFIG_CACHE.clear()

        config = load_config()

        assert config["credential_pool_strategies"]["openrouter"] == "round_robin"
